name: Build with Quality Check
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/build-with-shellcheck.yml
  bats-test:
    uses: ./.github/workflows/test-with-bats.yml
