name: Build with Quality Check
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  shellcheck:
    uses: ./.github/workflows/shellcheck.yml
  build-deb:
    uses: ./.github/workflows/build-deb.yml
    needs: shellcheck
  bats-test:
    uses: ./.github/workflows/test-with-bats.yml
